import { lazy } from 'react';

export const PAGE_TITLES: Record<string, string> = {
  'home': 'Início',
  'shop': 'Loja BP',
  'register': 'Criar Conta',
  'login': 'Acessar Conta',
  'profile': 'Meu Perfil',
  'about-bp': 'Quem Somos',
  'wallet': 'Carteira',
  'deposit': 'Recarga',
  'retirada': 'Retirada',
  'investimentos-fundo': 'Marketplace',
  'historico-fundos': 'Meus Pedidos',
  'ganhos-tarefas': 'Recompensas',
  'invite-page': 'Convidar Amigos',
  'security-verify': 'Segurança',
  'deposit-usdt-history': 'Histórico USDT',
  'subordinate-list': 'Equipe',
  'tasks': 'Minhas Tarefas',
};

export const DEFAULT_APP_TITLE = 'The Home Depot';

export const PAGES_CONFIG = {
  Home: lazy(() => import('./pages/Home')),
  Shop: lazy(() => import('./pages/ShopPage')),
  Wallet: lazy(() => import('./pages/Wallet')),
  Profile: lazy(() => import('./pages/Profile')),
  AddBank: lazy(() => import('./pages/AddBank')),
  Recharge: lazy(() => import('./pages/Recharge')),
  PurchaseHistory: lazy(() => import('./pages/PurchaseHistory')),
  ChangePassword: lazy(() => import('./pages/ChangePassword')),
  AccountHistory: lazy(() => import('./pages/AccountHistory')),
  Register: lazy(() => import('./pages/Register')),
  Withdraw: lazy(() => import('./pages/Withdraw')),
  Login: lazy(() => import('./pages/Login')),
  SecurityVerify: lazy(() => import('./pages/SecurityVerify')),
  Rewards: lazy(() => import('./pages/Rewards')),
  GiftChest: lazy(() => import('./pages/GiftChest')),
  RewardClaim: lazy(() => import('./pages/RewardClaim')),
  Info: lazy(() => import('./pages/Info')),
  AboutBP: lazy(() => import('./pages/AboutBP')),
  DepositUSDT: lazy(() => import('./pages/DepositUSDT')),
  DepositUSDTHistory: lazy(() => import('./pages/DepositUSDTHistory')),
  WalletHistory: lazy(() => import('./pages/WalletHistory')),
  WithdrawalHistory: lazy(() => import('./pages/WithdrawalHistory')),
  SubordinateList: lazy(() => import('./pages/SubordinateList')),
  InvitePage: lazy(() => import('./pages/InvitePage')),
  GuiaIndicacao: lazy(() => import('./components/GuiaIndicacao')),
  Tasks: lazy(() => import('./pages/Tasks')),
};
